CREATE DATABASE foodmap;
USE foodmap;

CREATE TABLE IF NOT EXISTS usuario(
ID INT AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL UNIQUE,
NOME VARCHAR(100) NOT NULL,
SENHA VARCHAR(20) NOT NULL,
ADM BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS restaurante(
COD_RESTAURANTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
DESCRICAO VARCHAR (1024) NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
IMAGEM VARCHAR(2048) NOT NULL

);

SELECT * FROM usuario;
select * from restaurante;


insert into usuario (EMAIL, NOME, SENHA, ADM) VALUES ("teste@gmail.com", "Teste", 123456789, false);
insert into usuario (NOME, EMAIL, SENHA, ADM) VALUES ("Admin", "linuxmint@gmail.com", "patoquack", true);
